# Docker Compose for local development

services:
  app:
    build: .
    ports:
      - "8547:8547"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./data/restaurant_booking.db
      - HOST=0.0.0.0
      - PORT=8547
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8547/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a reverse proxy for production-like setup
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app

volumes:
  app_data:
