name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: restaurant-booking-api
  REGION: europe-west1
  ARTIFACT_REGISTRY_REPO: restaurant-booking
  ARTIFACT_REGISTRY_LOCATION: europe-west1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/ --tb=short

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd web
          npm ci

      - name: Build frontend
        run: |
          cd web
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/postgress'

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev

      - name: Create Artifact Registry repository (if not exists)
        run: |
          gcloud artifacts repositories describe $ARTIFACT_REGISTRY_REPO \
            --location=$ARTIFACT_REGISTRY_LOCATION \
            --format="value(name)" || \
          gcloud artifacts repositories create $ARTIFACT_REGISTRY_REPO \
            --repository-format=docker \
            --location=$ARTIFACT_REGISTRY_LOCATION \
            --description="Docker repository for Restaurant Booking App"

      - name: Build and push Docker image
        run: |
          IMAGE_URL=$ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$SERVICE_NAME:$GITHUB_SHA
          docker build -f Dockerfile.cloudrun -t $IMAGE_URL .
          docker push $IMAGE_URL

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URL=$ARTIFACT_REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$SERVICE_NAME:$GITHUB_SHA
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_URL \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10 \
            --min-instances 0 \
            --port 8080 \
            --timeout 300 \
            --set-env-vars "ENVIRONMENT=production,DEBUG=false,SECRET_KEY=${{ secrets.SECRET_KEY }},NEON_DATABASE_URL=${{ secrets.NEON_DATABASE_URL }}"
